name: CI

on:
  push:
    branches: [ main, dev, ci ]
  pull_request:
    branches: [ main, dev ]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r etl/requirements.txt
          pip install pytest==8.3.5

  lint:
    name: Code Quality Checks
    needs: install
    steps:
      
      - name: Lint with ruff
        run: python -m ruff check etl tests

  test:
    name: Unit Tests
    needs: install
    steps:
      
      - name: Run unit tests
        run: python -m pytest -xvs -m "unit"
